### PR TITLE
add ridge cuml example

### PR DESCRIPTION
**Pull request by quasiben**

### CODE REVIEW

**Comment by mrocklin** [comment]
Thanks @quasiben !  I'm curious, was there a significant difference when compared to scikit-learn's GridSearchCV?

**Comment by mrocklin** [comment]
I think that we've been restarting and clearing outputs before merging in so far.  Happy either way though.  This would make diffs a bit more interpretable in the future.

**Comment by quasiben** [comment]
I updated the notebook with results.  There is significant difference:

| | sklearn | cuml | 
| -----------| --- | -----|
| **GridSearchCV** | 99.4 ms ± 9.53 ms | 6.09 s ± 40.7 ms |
| **dask-ml GridSearchCV**     | 417 ms ± 341 ms     |   655 ms ± 37.3 ms |

**Comment by jakirkham** [comment]
Should we go ahead and merge this?

**Comment by mrocklin** [comment]
Sure

**Pull request merged**
